image: freebsd/14.x
packages:
  - ruby
  - rubygem-gems
  - rubygem-rake
  - postgresql17-client
sources:
  - hg+https://hg.sr.ht/~ged/Observability
tasks:
  - setup: |
      cd Observability
      gem install --user-install -Ng
  - test: |
      export PATH=$PATH:$(ruby -r rubygems -e 'puts Gem.user_dir')/bin
      cd Observability
      COVERAGE=1 rspec -cfd
